# Generated by Django 3.2.22 on 2023-10-12 10:55

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('geeks_field', models.EmailField(max_length=200)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('num_of_guests', models.IntegerField()),
                ('booked_on', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['booked_on'],
            },
        ),
        migrations.CreateModel(
            name='Meals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('food_type', models.CharField(choices=[('fish', 'fish'), ('meat', 'meat'), ('vegan', 'vegan')], max_length=100)),
                ('meal_type', models.CharField(choices=[('starter', 'starter'), ('main', 'main'), ('dessert', 'dessert')], max_length=100)),
                ('featured_image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
            ],
            options={
                'ordering': ['price'],
            },
        ),
    ]
