# Generated by Django 3.2.22 on 2023-10-12 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='geeks_field',
            new_name='email',
        ),
    ]
