# Generated by Django 3.2.22 on 2023-10-12 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_rename_geeks_field_booking_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='num_of_guests',
            new_name='number_of_guests',
        ),
    ]
