# Generated by Django 3.2.22 on 2023-10-12 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_rename_num_of_guests_booking_number_of_guests'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Meals',
            new_name='Meal',
        ),
    ]
