# Generated by Django 3.2.22 on 2023-10-18 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_rename_meals_meal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='description',
            field=models.TextField(max_length=2000),
        ),
    ]
