# Generated by Django 3.2.22 on 2023-10-18 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_meal_meal_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='excerpt',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
