# Generated by Django 4.2.6 on 2023-10-20 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20231018_0935'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='number_of_guests',
            new_name='party_of',
        ),
    ]
