# Generated by Django 4.2.6 on 2023-10-25 09:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0008_rename_number_of_guests_booking_party_of'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='featured_image',
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='party_of',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='meal',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='meal',
            name='food_type',
            field=models.CharField(choices=[('fish', 'fish'), ('meat', 'meat'), ('vegan', 'vegan')], db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='meal',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
